apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp-mysql
  labels:
    name: simple-webapp-mysql
spec:
  selector:
    matchLabels:
      name: simple-webapp-mysql
  replicas: 1
  template:
    metadata:
      labels:
        name: simple-webapp-mysql
    spec:
      containers:
        - name: simple-webapp-mysql
          image: 740081625158.dkr.ecr.us-east-1.amazonaws.com/ecr-repo:v0.2
          ports:
            - containerPort: 81
          envFrom:
            - secretRef:
                name: db-secret
          env:
            - name: GROUP
              valueFrom: 
                configMapKeyRef:
                  name: webapp-config
                  key:  GROUP
          volumeMounts:
            - name: app-secret-volumes
              mountPath: "/opt/app-secret-volumes"
              readOnly: true
      volumes:
        - name: app-secret-volumes
          secret:
            secretName: db-secret
