apiVersion: v1
kind: ServiceAccount
metadata:
  name: clo835
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::033892266598:role/clo835-service-account-role
#automountServiceAccountToken: false